# Generated by Django 5.1.3 on 2025-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0003_remove_item_created_at_remove_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='province',
            field=models.CharField(max_length=100),
        ),
    ]
