# Generated by Django 5.1.3 on 2025-01-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0004_item_item_value_alter_item_address_alter_item_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='collateral_types',
        ),
        migrations.AddField(
            model_name='item',
            name='collateral_types',
            field=models.ManyToManyField(blank=True, to='ad_item.collateral'),
        ),
    ]
