# Generated by Django 5.1.3 on 2025-01-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0005_collateral_remove_item_collateral_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
