# Generated by Django 5.1.3 on 2025-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0006_item_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
