# Generated by Django 5.1.3 on 2025-01-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0007_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
