# Generated by Django 5.1.3 on 2025-01-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_item', '0008_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
